In [31]:
import os
from pathlib import Path
import geopandas as gpd
from shapely.geometry import Polygon
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path



f = os.getcwd()

In [11]:
data_path

PosixPath('/Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/datos')

In [ ]:
#/Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/codigo/01_build/03_output/kontur_boundaries_southamerica_20230628.gpkg

In [28]:
# Set up paths and directories
work_dir = Path(Path(f).parent.parent.parent)
output_path = Path(work_dir, '02_analysis','03_output')
data_path = Path(work_dir,'datos')

# ADMIN_DIVISIONS_PATH = work_dir / 'codigo' / '01_build' / '03_output'/ 'south_america_admin_divisions.gpkg'
ADMIN_DIVISIONS_PATH = work_dir / 'codigo' / '01_build' / '03_output'

In [94]:

southamerica_kontur = gpd.read_file(f"{work_dir}/codigo/01_build/03_output/population_density_south_america_results.gpkg")
africa_kontur = gpd.read_file(f"{work_dir}/codigo/01_build/03_output/kontur_boundaries_africa_20230628.gpkg")

In [95]:
southamerica_kontur.columns

Index(['GID_1', 'GID_0', 'COUNTRY', 'NAME_1', 'VARNAME_1', 'NL_NAME_1',
       'TYPE_1', 'ENGTYPE_1', 'CC_1', 'HASC_1', 'ISO_1', 'area_km2',
       'adjusted_population', 'population_density', 'geometry'],
      dtype='object')

In [100]:
southamerica_kontur[southamerica_kontur['GID_0'] == 'ARG'].adjusted_population.sum()

36130327.0

In [103]:

# southamerica_kontur[southamerica_kontur['GID_0'] == 'COL'].adjusted_population.sum()
southamerica_kontur['GID_0'].value_counts().reset_index()
southamerica_kontur.groupby('GID_0').apply(lambda x: x['adjusted_population'].sum() ).reset_index()

/var/folders/gh/2cf49j_x4q533sfszrhs7szc0000gn/T/ipykernel_5833/2711267128.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  southamerica_kontur.groupby('GID_0').apply(lambda x: x['adjusted_population'].sum() ).reset_index()

   GID_0           0
0    ARG  36130327.0
1    BOL   6301120.0
2    BRA    227792.0
3    CHL  18135662.0
4    COL         0.0
5    ECU         0.0
6    GUF         0.0
7    GUY         0.0
8    PER   2781135.0
9    PRY     94648.0
10   SUR         0.0
11   URY   3677581.0
12   VEN         0.0

In [104]:
southamerica_kontur.adjusted_population.sum()

67348265.0

In [22]:
southamerica_kontur_f=southamerica_kontur[southamerica_kontur['admin_level'] == 4].copy()

In [90]:
# Create column with country 
southamerica_kontur['hasc_country'] = southamerica_kontur['hasc'].str[0:2] 
africa_kontur['hasc_country'] = africa_kontur['hasc'].str[0:2] 
southamerica_kontur.hasc_country.value_counts().reset_index()

   hasc_country  count
0            BR     30
1            PE     26
2            AR     25
3            PY     19
4            CL     17
5            BO     10
6            GF      2
7            VE      1
8            EC      1
9            UY      1
10           CO      1
11           SR      1
12           GY      1

In [24]:
southamerica_kontur.query('hasc_country == ""')

,admin_level,osm_admin_level,name,name_en,population,hasc,region,geometry,hasc_country
10,2.0,2,Chile,Chile,18421842.0,CL,South America,"MULTIPOLYGON (((-76.04944 -49.09999, -76.04939...",CL
21,4.0,4,Región de Antofagasta,None,575312.0,CL.AN,South America,"MULTIPOLYGON (((-70.73714 -25.81646, -70.73705...",CL
22,4.0,4,Región del Maule,None,1029985.0,CL.ML,South America,"MULTIPOLYGON (((-72.78574 -35.97834, -72.78570...",CL
23,4.0,4,Región de Tarapacá,None,348384.0,CL.TP,South America,"MULTIPOLYGON (((-70.28622 -19.22896, -70.28588...",CL
24,4.0,4,Región de Arica y Parinacota,None,172737.0,CL.AP,South America,"MULTIPOLYGON (((-70.37883 -18.35012, -70.37813...",CL
26,4.0,4,Región de Coquimbo,None,752085.0,CL.CO,South America,"MULTIPOLYGON (((-71.71563 -30.64994, -71.71559...",CL
28,4.0,4,Región de Atacama,None,284812.0,CL.AT,South America,"MULTIPOLYGON (((-71.52566 -28.98670, -71.52562...",CL
79,4.0,4,Región del Libertador General Bernardo O'Higgins,None,912392.0,CL.LI,South America,"MULTIPOLYGON (((-72.05592 -34.68631, -72.05539...",CL
81,4.0,4,Región Metropolitana de Santiago,None,7332785.0,CL.RM,South America,"MULTIPOLYGON (((-71.71485 -33.94850, -71.71474...",CL
82,4.0,4,Región de Valparaíso,None,1807749.0,CL.VS,South America,"MULTIPOLYGON (((-71.84334 -33.91923, -71.84329...",CL
83,4.0,4,Región del Biobío,None,2019293.0,CL.BI,South America,"MULTIPOLYGON (((-73.68503 -37.36667, -73.68503...",CL
106,4.0,4,Región de Los Lagos,None,894759.0,CL.LG,South America,"MULTIPOLYGON (((-74.84554 -43.54429, -74.84552...",CL
107,4.0,4,Región de Ñuble,None,465654.0,CL.NB,South America,"MULTIPOLYGON (((-72.88578 -36.44492, -72.88565...",CL
108,4.0,4,Región de Los Ríos,None,379346.0,CL.LR,South America,"MULTIPOLYGON (((-73.72509 -40.19993, -73.72509...",CL
111,4.0,4,Región Aysén del General Carlos Ibáñez del Campo,None,115200.0,CL.AI,South America,"MULTIPOLYGON (((-75.70038 -48.78550, -75.69479...",CL
121,4.0,4,Región de Magallanes y de la Antártica Chilena,Region of Magallanes and Chilean Antarctica,163864.0,CL.MA,South America,"MULTIPOLYGON (((-75.72252 -49.14639, -75.70038...",CL
128,4.0,4,Región de la Araucanía,None,1009385.0,CL.AR,South America,"MULTIPOLYGON (((-73.51907 -38.48157, -73.51907...",CL

In [40]:
# Group southamerica_kontur by hasc_country and add population
southamerica_kontur.groupby('hasc_country').apply(lambda x: x['population'].sum() ).reset_index()

/var/folders/gh/2cf49j_x4q533sfszrhs7szc0000gn/T/ipykernel_4207/3991286262.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  southamerica_kontur.groupby('hasc_country').apply(lambda x: x['population'].sum() ).reset_index()

   hasc_country            0
0            AR   85557326.0
1            BO   20237010.0
2            BR  441417564.0
3            CL   36685584.0
4            CO   48637464.0
5            EC   18728680.0
6            GF     586753.0
7            GY     786917.0
8            PE   61329988.0
9            PY   14024442.0
10           SR     586725.0
11           UY    3475418.0
12           VE   29618967.0

In [37]:
# Create column with country 
africa_kontur['hasc_country'] = africa_kontur['hasc'].str[0:2] 
africa_kontur.hasc_country.value_counts().reset_index()

   hasc_country  count
0            NG     38
1            SL     18
2            ZA     10
3            EG      3
4            TG      3
5            TD      2
6            SN      2
7            MA      2
8            CG      1
9            AO      1
10           GA      1
11           GQ      1
12           CD      1
13           UG      1
14           KE      1
15           CF      1
16           NA      1
17           DZ      1
18           BI      1
19           SO      1
20           ET      1
21           DJ      1
22           TZ      1
23           ZM      1
24           ZW      1
25           MZ      1
26           MW      1
27           ER      1
28           RW      1
29           SD      1
30           BJ      1
31           NE      1
32           CI      1
33           LY      1
34           MR      1
35           MG      1
36           SZ      1
37           GM      1
38           GW      1
39           SC      1
40           GN      1
41           SS      1
42           BW      1
43           ML      1
44           CV      1
45           KM      1
46           LR      1
47           MU      1
48           ST      1
49           GH      1
50           LS      1
51           BF      1
52           TN      1
53           CM      1

13

In [27]:
southamerica_kontur[southamerica_kontur['hasc'].str.startswith('VE')]

,admin_level,osm_admin_level,name,name_en,population,hasc,region,geometry
1,2.0,2,Venezuela,Venezuela,29618967.0,VE,South America,"MULTIPOLYGON (((-73.35296 9.21753, -73.35232 9..."

In [59]:
southamerica_kontur.head(1)
southamerica_kontur['hasc_country'].unique()

array(['BR', 'VE', 'BO', 'EC', 'UY', 'CO', 'PY', 'SR', 'GY', 'AR', 'CL',
       'PE', 'GF'], dtype=object)

# South America

In [87]:
def create_population_density_plots(gdf, continent, output_dir='density_plots'):
    """
    Create population density plots for each country using appropriate ESRI projections.
    
    Parameters:
    -----------
    gdf : GeoDataFrame
        Must contain columns: osm_admin_level, name, population, geometry
    continent : str
        Either 'south_america' or 'africa' to determine the appropriate projection
    output_dir : str
        Directory where plots will be saved
    """
    # Create output directory if it doesn't exist
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    # Set the appropriate ESRI projection based on continent
    if continent.lower() == 'south_america':
        # South America Albers Equal Area Conic
        proj_crs = 'esri:102033'
    elif continent.lower() == 'africa':
        # Africa Albers Equal Area Conic
        proj_crs = 'esri:102022'
    else:
        raise ValueError("Continent must be either 'south_america' or 'africa'")
    
    # Project the data
    gdf_projected = gdf.to_crs(proj_crs)
    
    print("The data has been projected to", gdf_projected.crs.name)
    print("The columns pre filter are", gdf_projected.columns, f"dim: {gdf_projected.shape}")

    gdf_filtered = gdf_projected[gdf_projected['osm_admin_level'] == "4"].copy()
    print("The columns filter are", gdf_filtered.columns, f"dim: {gdf_filtered.shape}")

    
    # Calculate area in square kilometers and population density
    gdf_filtered['area_km2'] = gdf_filtered.geometry.area / 10**6  # Convert m² to km²
    gdf_filtered['pop_density'] = gdf_filtered['population'] / gdf_filtered['area_km2']
    print(f"The columns filter and popdensity are {gdf_filtered.columns} and dim {gdf_filtered.shape}")
    # Calculate quintiles for each country
    print("Pre loop")
    print("Iterating on ", gdf_filtered['hasc_country'].unique())
    for country in gdf_filtered['hasc_country'].unique():
        print("Calculating quintiles and density for", country)
        country_data = gdf_filtered[gdf_filtered['hasc_country'] == country]
        
        # Skip if no valid population density values
        if country_data['pop_density'].isna().all():
            print(f"Skipping {country} due to missing population density values")
            continue
            
        # Calculate quintiles for this country
        try:
            quintiles = pd.qcut(country_data['pop_density'], 
                              q=5, 
                              labels=['Q1 (Lowest)', 'Q2', 'Q3', 'Q4', 'Q5 (Highest)'])
            
            country_data.loc[country_data.index, 'density_quintile'] = quintiles
            print(f"Creating quintiles column {country_data.columns}")
            
            # Create the plot
            fig, ax = plt.subplots(1, 1, figsize=(15, 15))
            
            # Plot the country data
            country_data.plot(column='density_quintile',
                            categorical=True,
                            legend=True,
                            ax=ax,
                            cmap='YlOrRd',
                            legend_kwds={'title': 'Population Density\nQuintiles',
                                       'bbox_to_anchor': (1.3, 1)})
            # Plot the country data
            country_data.plot(column='density_quintile',
                              categorical=True,
                              legend=True,
                              ax=ax,
                              cmap='YlOrRd',
                              legend_kwds={'title': 'Population Density\nQuintiles',
                                           'bbox_to_anchor': (1.3, 1),
                                           'frameon': False,  # Removes the legend box outline
                                            'fontsize': 12,    # Increases font size of legend labels
                                            'title_fontsize': 14})  # Increases font size of legend title
            # Calculate total population
            total_pop = country_data['population'].sum()
            
            # Add title and caption
            plt.title(f'Population Density by Administrative Division\n{country}', 
                     pad=20, 
                     size=16)
            
            plt.figtext(0.5, 0.02, 
                       f'Total Population: {total_pop:,.0f}\nProjection: {proj_crs}',
                       ha='center',
                       bbox=dict(facecolor='white', alpha=0.8))
            
            # Remove axes
            ax.axis('off')
            
            # Adjust layout to prevent text cutoff
            plt.tight_layout()
            
            # Save the plot
            print("Saving plot at ", f'{output_dir}/{country.replace(" ", "_")}_density.png')
            plt.savefig(f'{output_dir}/{country.replace(" ", "_")}_density.png', 
                       bbox_inches='tight',
                       dpi=300)
            plt.close()
            
        except ValueError as e:
            print(f"Could not create quintiles for {country}: {str(e)}")
            continue
    
    return gdf_filtered

In [92]:

# Example usage for South America
southamerica_density = create_population_density_plots(
    southamerica_kontur, 
    continent='south_america', 
    output_dir=f'{output_path}/southamerica_density_plots'
)

The data has been projected to South_America_Albers_Equal_Area_Conic
The columns pre filter are Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country'],
      dtype='object') dim: (135, 9)
The columns filter are Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country'],
      dtype='object') dim: (117, 9)
The columns filter and popdensity are Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2',
       'pop_density'],
      dtype='object') and dim (117, 11)
Pre loop
Iterating on  ['PE' 'AR' 'BR' 'CL' 'BO' 'PY']
Calculating quintiles and density for PE
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots/PE_density.png
Calculating quintiles and density for AR
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots/AR_density.png
Calculating quintiles and density for BR
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots/BR_density.png
Calculating quintiles and density for CL
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots/CL_density.png
Calculating quintiles and density for BO
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')
Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots/BO_density.png

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Calculating quintiles and density for PY
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')
Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots/PY_density.png

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [41]:
f'{output_path}/southamerica_density_plots'

'/Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/southamerica_density_plots'

In [30]:
# Example usage for South America
density_data = create_population_density_plots(southamerica_kontur, )

/var/folders/gh/2cf49j_x4q533sfszrhs7szc0000gn/T/ipykernel_5833/3117776277.py:25: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf_filtered['area_km2'] = gdf_filtered.geometry.area / 10**6  # Convert m² to km²

In [93]:
# Example usage for Africa
africa_density = create_population_density_plots(
    africa_kontur, 
    continent='africa', 
    output_dir=f'{output_path}/africa_density_plots'
    )

The data has been projected to Africa_Albers_Equal_Area_Conic
The columns pre filter are Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country'],
      dtype='object') dim: (124, 9)
The columns filter are Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country'],
      dtype='object') dim: (55, 9)
The columns filter and popdensity are Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2',
       'pop_density'],
      dtype='object') and dim (55, 11)
Pre loop
Iterating on  ['NG' 'ZA' 'TD' 'SL' 'MA' 'EG' 'SN']
Calculating quintiles and density for NG
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')
Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/africa_density_plots/NG_density.png

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Calculating quintiles and density for ZA
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')
Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/africa_density_plots/ZA_density.png

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Calculating quintiles and density for TD
Could not create quintiles for TD: Bin edges must be unique: Index([2819.8097955963867, 2819.8097955963867, 2819.8097955963867,
       2819.8097955963867, 2819.8097955963867, 2819.8097955963867],
      dtype='float64', name='pop_density').
You can drop duplicate edges by setting the 'duplicates' kwarg
Calculating quintiles and density for SL
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')
Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/africa_density_plots/SL_density.png

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Calculating quintiles and density for MA
Could not create quintiles for MA: Bin edges must be unique: Index([335.7549834330274, 335.7549834330274, 335.7549834330274,
       335.7549834330274, 335.7549834330274, 335.7549834330274],
      dtype='float64', name='pop_density').
You can drop duplicate edges by setting the 'duplicates' kwarg
Calculating quintiles and density for EG
Creating quintiles column Index(['admin_level', 'osm_admin_level', 'name', 'name_en', 'population',
       'hasc', 'region', 'geometry', 'hasc_country', 'area_km2', 'pop_density',
       'density_quintile'],
      dtype='object')
Saving plot at  /Users/upar/Library/CloudStorage/OneDrive-Universidaddelosandes/capacidad-estatal/02_analysis/03_output/africa_density_plots/EG_density.png

/opt/anaconda3/envs/sc/lib/python3.9/site-packages/geopandas/geodataframe.py:1543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

Calculating quintiles and density for SN
Could not create quintiles for SN: Bin edges must be unique: Index([16.536912602552515, 16.536912602552515, 16.536912602552515,
       16.536912602552515, 16.536912602552515, 16.536912602552515],
      dtype='float64', name='pop_density').
You can drop duplicate edges by setting the 'duplicates' kwarg